// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJHaN-C5CScznAK9zR60pEB2TRqaJygg',
    appId: '1:89298882636:web:ea3d1b5073f1257a4ae4e9',
    messagingSenderId: '89298882636',
    projectId: 'dhatnoon-6caaa',
    authDomain: 'dhatnoon-6caaa.firebaseapp.com',
    storageBucket: 'dhatnoon-6caaa.appspot.com',
    measurementId: 'G-0F5SBMJ5ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdcHeNOcWNBPIYjysEUaSQDLyTU7NQOg8',
    appId: '1:89298882636:android:a394af1ad8717ca34ae4e9',
    messagingSenderId: '89298882636',
    projectId: 'dhatnoon-6caaa',
    storageBucket: 'dhatnoon-6caaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAofzNEP-rOmTV2s7mWezFodCjhhi1XheM',
    appId: '1:89298882636:ios:5c06c2414867458d4ae4e9',
    messagingSenderId: '89298882636',
    projectId: 'dhatnoon-6caaa',
    storageBucket: 'dhatnoon-6caaa.appspot.com',
    iosBundleId: 'com.aeronex.dhatnoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAofzNEP-rOmTV2s7mWezFodCjhhi1XheM',
    appId: '1:89298882636:ios:a579a2a10040a0a54ae4e9',
    messagingSenderId: '89298882636',
    projectId: 'dhatnoon-6caaa',
    storageBucket: 'dhatnoon-6caaa.appspot.com',
    iosBundleId: 'com.aeronex.dhatnoon.RunnerTests',
  );
}
